version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: artemis
    container_name: artemis
    restart: unless-stopped
    ports:
      - "8008:80"
    volumes:
      - ./:/var/www/html

networks:
  default:
    driver: bridge
